2023-07-07 22:24:11,158 - INFO - Starting transfer_files
2023-07-07 22:24:11,234 - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2023-07-07 22:24:11,338 - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2023-07-07 22:24:11,389 - INFO - Getting source bucket contents
2023-07-07 22:24:12,118 - INFO - Starting file transfer
2023-07-07 22:24:12,119 - INFO - Transferring file: .git/HEAD
2023-07-07 22:24:12,247 - ERROR - An error occurred during file transfer:
2023-07-07 22:24:12,247 - ERROR - [Errno 2] No such file or directory: '/tmp/.git/HEAD'
2023-07-07 22:24:12,249 - ERROR - Traceback (most recent call last):
  File "/Users/joelhutson/Projects/aws_s3_transfer_docker/functions.py", line 163, in transfer_files
    progress_download(source_client, source_bucket, file, file_path, progress_var)
  File "/Users/joelhutson/Projects/aws_s3_transfer_docker/functions.py", line 106, in progress_download
    with open(file_path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.git/HEAD'

2023-07-07 22:24:12,249 - INFO - Finished transfer_files
